name: metrics
channels:
- peterjc123
- menpo
- conda-forge
- defaults
- anaconda
- powerai
dependencies:
- python=3.6
- pytorch
- torchvision==0.2.1
- scipy
- scikit-image
- scikit-learn
- tensorflow-gpu==1.12
- gin-config==0.1.4
- opencv3
- pip:
  - dominate==2.3.1
  - Pillow==5.0.0
  - numpy==1.15.0
  - visdom==0.1.7
  - matplotlib
  - tqdm